package model

// GENERATED BY POGO. DO NOT EDIT.

// Delete the Report from the database.
func (r *Reports) Delete(id *string) (err error) {
 // sql query
 const sqlstr = `
    DELETE FROM jack.reports
    WHERE id = $1
  `

 // run query
 DBLog(sqlstr, id)
 _, err = r.DB.Exec(sqlstr, id)
 if err != nil {
  return err
 }

 return nil
}
