package model

import (
 "strings"

 "github.com/pkg/errors"
)

// GENERATED BY POGO. DO NOT EDIT.

// Insert the StandupTeammate to the database.
func (st *StandupTeammates) Insert(stst *StandupTeammate) (standupteammate StandupTeammate, err error) {
 // get all the non-nil fields and prepare them for the query
 c, i, v := querySlices(st.getFields(stst), 0)

 // sql insert query, primary key provided by sequence
 sqlstr := `
	INSERT INTO jack.standups_teammates (` + strings.Join(c, ", ") + `)
	VALUES (` + strings.Join(i, ", ") + `)
	RETURNING standup_id, teammate_id, team_owner, created_at, updated_at`

 DBLog(sqlstr, v...)
 row := st.DB.QueryRow(sqlstr, v...)
 err = row.Scan(&standupteammate.StandupID, &standupteammate.TeammateID, &standupteammate.TeamOwner, &standupteammate.CreatedAt, &standupteammate.UpdatedAt)
 if err != nil {
  return standupteammate, errors.Wrap(err, "could not insert into 'standups_teammates'")
 }

 return standupteammate, nil
}
