package model

// GENERATED BY POGO. DO NOT EDIT.

// Find a team by id
func (s *Standups) Find(id *string) (standup Standup, err error) {
 // sql select query, primary key provided by sequence
 sqlstr := `
    SELECT id, name, slack_channel_id, time, timezone, questions, team_id, created_at, updated_at
    FROM jack.standups
    WHERE id = $1`

 XOLog(sqlstr, id)
 row := s.DB.QueryRow(sqlstr, id)
 err = row.Scan(&standup.ID, &standup.Name, &standup.SlackChannelID, &standup.Time, &standup.Timezone, &standup.Questions, &standup.TeamID, &standup.CreatedAt, &standup.UpdatedAt)
 if err != nil {
  return standup, err
 }

 return standup, nil
}
