package model

// GENERATED BY POGO. DO NOT EDIT.

// Delete the Teammate from the database.
func (t *Teammates) Delete(id *string) (err error) {
 // sql query
 const sqlstr = `
    DELETE FROM jack.teammates
    WHERE id = $1
  `

 // run query
 DBLog(sqlstr, id)
 _, err = t.DB.Exec(sqlstr, id)
 if err != nil {
  return err
 }

 return nil
}
