package enum

import "database/sql/driver"

// GENERATED BY POGO. DO NOT EDIT.

// Currency is the `currency` enum type from `1`.
type Currency string

const (

	// CurrencyBtcUsd is the 'BTC-USD' Currency.
	CurrencyBtcUsd = Currency("BTC-USD")

	// CurrencyEthUsd is the 'ETH-USD' Currency.
	CurrencyEthUsd = Currency("ETH-USD")
)

// Value satisfies the sql/driver.Valuer interface for Currency.
func (currency Currency) Value() (driver.Value, error) {
	return string(currency), nil
}
