package enum

import "database/sql/driver"

// GENERATED BY POGO. DO NOT EDIT.

// Exchange is the `exchange` enum type from `1`.
type Exchange string

const (

	// ExchangeGdax is the 'GDAX' Exchange.
	ExchangeGdax = Exchange("GDAX")
)

// Value satisfies the sql/driver.Valuer interface for Exchange.
func (exchange Exchange) Value() (driver.Value, error) {
	return string(exchange), nil
}
