package jack

import "strings"

// GENERATED BY POGO. DO NOT EDIT.

// Insert the Conversation to the database.
func (c *Conversations) Insert(cc *Conversation) (conversation Conversation, err error) {
	// get all the non-nil fields and prepare them for the query
	c, i, v := querySlices(c.getFields(cc), 0)

	// sql insert query, primary key provided by sequence
	sqlstr := `
	INSERT INTO public.conversations (` + strings.Join(c, ", ") + `)
	VALUES (` + strings.Join(i, ", ") + `)
	RETURNING "id", "user_id", "topic", "context", "state", "created", "updated"`

	DBLog(sqlstr, v...)
	row := c.DB.QueryRow(sqlstr, v...)
	err = row.Scan(&conversation.ID, &conversation.UserID, &conversation.Topic, &conversation.Context, &conversation.State, &conversation.Created, &conversation.Updated)
	if err != nil {
		return conversation, err
	}

	return conversation, nil
}
