package jack

import "github.com/matthewmueller/pgx"

// GENERATED BY POGO. DO NOT EDIT.

// FindOne Cron by a condition
func (c *Crons) FindOne(condition string, params ...interface{}) (cron Cron, err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "id", "frequency", "job", "tz", "start_time", "end_time", "retry", "created", "updated"
    FROM public.crons
    WHERE ` + condition

	DBLog(sqlstr, params...)
	row := c.DB.QueryRow(sqlstr, params...)
	err = row.Scan(&cron.ID, &cron.Frequency, &cron.Job, &cron.Tz, &cron.StartTime, &cron.EndTime, &cron.Retry, &cron.Created, &cron.Updated)
	if err != nil {
		if err == pgx.ErrNoRows {
			return cron, ErrCronNotFound
		}
		return cron, err
	}

	return cron, nil
}
