package jack

import "strings"

// GENERATED BY POGO. DO NOT EDIT.

// Insert the Report to the database.
func (r *Reports) Insert(rr *Report) (report Report, err error) {
	// get all the non-nil fields and prepare them for the query
	c, i, v := querySlices(r.getFields(rr), 0)

	// sql insert query, primary key provided by sequence
	sqlstr := `
	INSERT INTO public.reports (` + strings.Join(c, ", ") + `)
	VALUES (` + strings.Join(i, ", ") + `)
	RETURNING "id", "user_id", "timestamp", "questions", "standup_id", "status"`

	DBLog(sqlstr, v...)
	row := r.DB.QueryRow(sqlstr, v...)
	err = row.Scan(&report.ID, &report.UserID, &report.Timestamp, &report.Questions, &report.StandupID, &report.Status)
	if err != nil {
		return report, err
	}

	return report, nil
}
