package jack

import (
	"github.com/matthewmueller/pgx"
	"github.com/satori/go.uuid"
)

// GENERATED BY POGO. DO NOT EDIT.

// Find a Report by "id"
func (r *Reports) Find(id *uuid.UUID) (report Report, err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "id", "user_id", "timestamp", "questions", "standup_id", "status", "created_at", "updated_at"
    FROM jack.reports
    WHERE "id" = $1`

	DBLog(sqlstr, id)
	row := r.DB.QueryRow(sqlstr, id)
	err = row.Scan(&report.ID, &report.UserID, &report.Timestamp, &report.Questions, &report.StandupID, &report.Status, &report.CreatedAt, &report.UpdatedAt)
	if err != nil {
		if err == pgx.ErrNoRows {
			return report, ErrReportNotFound
		}
		return report, err
	}

	return report, nil
}
