package jack

import "strings"

// GENERATED BY POGO. DO NOT EDIT.

// Insert the Report to the database.
func (r *Reports) Insert(rr *Report) (report Report, err error) {
	// get all the non-nil fields and prepare them for the query
	_c, _i, _v := querySlices(r.getFields(rr), 0)

	// sql insert query, primary key provided by sequence
	sqlstr := `
	INSERT INTO jack.reports (` + strings.Join(_c, ", ") + `)
	VALUES (` + strings.Join(_i, ", ") + `)
	RETURNING "id", "user_id", "timestamp", "questions", "standup_id", "status", "created_at", "updated_at"`

	DBLog(sqlstr, _v...)
	row := r.DB.QueryRow(sqlstr, _v...)
	err = row.Scan(&report.ID, &report.UserID, &report.Timestamp, &report.Questions, &report.StandupID, &report.Status, &report.CreatedAt, &report.UpdatedAt)
	if err != nil {
		return report, err
	}

	return report, nil
}
