package jack

import (
	"github.com/matthewmueller/pgx"
)

// GENERATED BY POGO. DO NOT EDIT.

// Delete the Report from the database.
func (r *Reports) Delete(id *int) (err error) {
	// sql query
	sqlstr := `DELETE FROM public.reports WHERE "id" = $1`

	// run query
	DBLog(sqlstr, id)
	_, err = r.DB.Exec(sqlstr, id)
	if err != nil {
		if err == pgx.ErrNoRows {
			return ErrReportNotFound
		}
		return err
	}

	return nil
}
