package jack

import "strings"

// GENERATED BY POGO. DO NOT EDIT.

// Insert the Standup to the database.
func (s *Standups) Insert(ss *Standup) (standup Standup, err error) {
	// get all the non-nil fields and prepare them for the query
	c, i, v := querySlices(s.getFields(ss), 0)

	// sql insert query, primary key provided by sequence
	sqlstr := `
	INSERT INTO public.standups (` + strings.Join(c, ", ") + `)
	VALUES (` + strings.Join(i, ", ") + `)
	RETURNING "id", "channel_id", "time", "tz", "questions", "created", "updated", "owner", "team_id", "name"`

	DBLog(sqlstr, v...)
	row := s.DB.QueryRow(sqlstr, v...)
	err = row.Scan(&standup.ID, &standup.ChannelID, &standup.Time, &standup.Tz, &standup.Questions, &standup.Created, &standup.Updated, &standup.Owner, &standup.TeamID, &standup.Name)
	if err != nil {
		return standup, err
	}

	return standup, nil
}
