package jack

import (
	"github.com/matthewmueller/pgx"
	"github.com/satori/go.uuid"
)

// GENERATED BY POGO. DO NOT EDIT.

// Delete the Standup from the database.
func (s *Standups) Delete(id *uuid.UUID) (err error) {
	// sql query
	sqlstr := `DELETE FROM jack.standups WHERE "id" = $1`

	// run query
	DBLog(sqlstr, id)
	_, err = s.DB.Exec(sqlstr, id)
	if err != nil {
		if err == pgx.ErrNoRows {
			return ErrStandupNotFound
		}
		return err
	}

	return nil
}

// DeleteBySlackChannelID find a Standup
func (s *Standups) DeleteBySlackChannelID(slackchannelid *string) (err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `DELETE FROM jack.standups WHERE "slack_channel_id" = $1`

	DBLog(sqlstr, slackchannelid)
	_, err = s.DB.Exec(sqlstr, slackchannelid)
	if err != nil {
		if err == pgx.ErrNoRows {
			return ErrStandupNotFound
		}
		return err
	}

	return nil
}
