package jack

import "github.com/matthewmueller/pgx"

// GENERATED BY POGO. DO NOT EDIT.

// FindOne Standup by a condition
func (s *Standups) FindOne(condition string, params ...interface{}) (standup Standup, err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "id", "name", "slack_channel_id", "time", "timezone", "questions", "team_id", "created_at", "updated_at"
    FROM jack.standups
    WHERE ` + condition

	DBLog(sqlstr, params...)
	row := s.DB.QueryRow(sqlstr, params...)
	err = row.Scan(&standup.ID, &standup.Name, &standup.SlackChannelID, &standup.Time, &standup.Timezone, &standup.Questions, &standup.TeamID, &standup.CreatedAt, &standup.UpdatedAt)
	if err != nil {
		if err == pgx.ErrNoRows {
			return standup, ErrStandupNotFound
		}
		return standup, err
	}

	return standup, nil
}
