package jack

// GENERATED BY POGO. DO NOT EDIT.

// DeleteMany delete many Standups by a condition
func (s *Standups) DeleteMany(condition string, params ...interface{}) (err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `DELETE FROM jack.standups WHERE ` + condition

	DBLog(sqlstr, params...)
	_, err = s.DB.Exec(sqlstr, params...)
	if err != nil {
		return err
	}

	return nil
}
