package jack

import (
	"github.com/matthewmueller/pgx"
)

// GENERATED BY POGO. DO NOT EDIT.

// Delete the Teammate from the database.
func (t *Teammates) Delete(id *int) (err error) {
	// sql query
	sqlstr := `DELETE FROM public.teammates WHERE "id" = $1`

	// run query
	DBLog(sqlstr, id)
	_, err = t.DB.Exec(sqlstr, id)
	if err != nil {
		if err == pgx.ErrNoRows {
			return ErrTeammateNotFound
		}
		return err
	}

	return nil
}

// DeleteBySlackID find a Teammate
func (t *Teammates) DeleteBySlackID(slackid *string) (err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `DELETE FROM public.teammates WHERE "slack_id" = $1`

	DBLog(sqlstr, slackid)
	_, err = t.DB.Exec(sqlstr, slackid)
	if err != nil {
		if err == pgx.ErrNoRows {
			return ErrTeammateNotFound
		}
		return err
	}

	return nil
}
