package jack

import "github.com/matthewmueller/pgx"

// GENERATED BY POGO. DO NOT EDIT.

// FindOne TeammateStandup by a condition
func (ts *TeammateStandups) FindOne(condition string, params ...interface{}) (teammatestandup TeammateStandup, err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "id", "standup_id", "teammate_id", "time", "status"
    FROM public.teammate_standups
    WHERE ` + condition

	DBLog(sqlstr, params...)
	row := ts.DB.QueryRow(sqlstr, params...)
	err = row.Scan(&teammatestandup.ID, &teammatestandup.StandupID, &teammatestandup.TeammateID, &teammatestandup.Time, &teammatestandup.Status)
	if err != nil {
		if err == pgx.ErrNoRows {
			return teammatestandup, ErrTeammateStandupNotFound
		}
		return teammatestandup, err
	}

	return teammatestandup, nil
}
