package jack

import "strings"

// GENERATED BY POGO. DO NOT EDIT.

// Insert the Teammate to the database.
func (t *Teammates) Insert(tt *Teammate) (teammate Teammate, err error) {
	// get all the non-nil fields and prepare them for the query
	c, i, v := querySlices(t.getFields(tt), 0)

	// sql insert query, primary key provided by sequence
	sqlstr := `
	INSERT INTO public.teammates (` + strings.Join(c, ", ") + `)
	VALUES (` + strings.Join(i, ", ") + `)
	RETURNING "id", "slack_id", "team_id", "created", "updated"`

	DBLog(sqlstr, v...)
	row := t.DB.QueryRow(sqlstr, v...)
	err = row.Scan(&teammate.ID, &teammate.SlackID, &teammate.TeamID, &teammate.Created, &teammate.Updated)
	if err != nil {
		return teammate, err
	}

	return teammate, nil
}
