package jack

import (
	"github.com/matthewmueller/pgx"
)

// GENERATED BY POGO. DO NOT EDIT.

// Delete the TeammateStandup from the database.
func (ts *TeammateStandups) Delete(id *int) (err error) {
	// sql query
	sqlstr := `DELETE FROM public.teammate_standups WHERE "id" = $1`

	// run query
	DBLog(sqlstr, id)
	_, err = ts.DB.Exec(sqlstr, id)
	if err != nil {
		if err == pgx.ErrNoRows {
			return ErrTeammateStandupNotFound
		}
		return err
	}

	return nil
}

// DeleteByStandupIDAndTeammateID find a TeammateStandup
func (ts *TeammateStandups) DeleteByStandupIDAndTeammateID(standupid *int, teammateid *int) (err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `DELETE FROM public.teammate_standups WHERE "standup_id" = $1 AND "teammate_id" = $2`

	DBLog(sqlstr, standupid, teammateid)
	_, err = ts.DB.Exec(sqlstr, standupid, teammateid)
	if err != nil {
		if err == pgx.ErrNoRows {
			return ErrTeammateStandupNotFound
		}
		return err
	}

	return nil
}
