package jack

// GENERATED BY POGO. DO NOT EDIT.

// DeleteMany delete many Teammates by a condition
func (t *Teammates) DeleteMany(condition string, params ...interface{}) (err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `DELETE FROM jack.teammates WHERE ` + condition

	DBLog(sqlstr, params...)
	_, err = t.DB.Exec(sqlstr, params...)
	if err != nil {
		return err
	}

	return nil
}
