package jack

import "strings"

// GENERATED BY POGO. DO NOT EDIT.

// Insert the Team to the database.
func (t *Teams) Insert(tt *Team) (team Team, err error) {
	// get all the non-nil fields and prepare them for the query
	c, i, v := querySlices(t.getFields(tt), 0)

	// sql insert query, primary key provided by sequence
	sqlstr := `
	INSERT INTO public.teams (` + strings.Join(c, ", ") + `)
	VALUES (` + strings.Join(i, ", ") + `)
	RETURNING "id", "team_access_token", "bot_access_token", "trial_ends", "team_name", "team_id", "bot_user_id", "scope", "email", "stripe_id", "active", "created", "updated", "free_teammates", "cost_per_user"`

	DBLog(sqlstr, v...)
	row := t.DB.QueryRow(sqlstr, v...)
	err = row.Scan(&team.ID, &team.TeamAccessToken, &team.BotAccessToken, &team.TrialEnds, &team.TeamName, &team.TeamID, &team.BotUserID, &team.Scope, &team.Email, &team.StripeID, &team.Active, &team.Created, &team.Updated, &team.FreeTeammates, &team.CostPerUser)
	if err != nil {
		return team, err
	}

	return team, nil
}
