package pogo

import (
	"io/ioutil"
	"os"
	"path"
	"strings"

	"github.com/pkg/errors"
)

// Write out the models
func Write(models map[string]string, outpath string) error {
	if _, e := os.Stat(outpath); os.IsNotExist(e) {
		if ee := os.MkdirAll(outpath, os.ModePerm); ee != nil {
			return ee
		}
	}

	for basepath, model := range models {
		filepath := path.Join(outpath, basepath)

		if _, e := os.Stat(filepath); e == nil {
			buf, ee := ioutil.ReadFile(filepath)
			if ee != nil {
				return ee
			}
			if !strings.Contains(string(buf), "// GENERATED BY POGO") {
				return errors.New("Refusing to write over `" + filepath + "`. Please rename this file.")
			}
		}

		if e := ioutil.WriteFile(filepath, []byte(model), os.ModePerm); e != nil {
			return errors.Wrapf(e, "unable to write out `%s`", filepath)
		}
	}

	return nil
}
