package tempo

// GENERATED BY POGO. DO NOT EDIT.

// Delete the Active from the database.
func (a *Actives) Delete(id *string) (err error) {
 // sql query
 const sqlstr = `
    DELETE FROM public.actives
    WHERE id = $1
  `

 // run query
 DBLog(sqlstr, id)
 _, err = a.DB.Exec(sqlstr, id)
 if err != nil {
  return err
 }

 return nil
}
