package tempo

import "strings"

// GENERATED BY POGO. DO NOT EDIT.

// Insert the Active to the database.
func (a *Actives) Insert(aa *Active) (active Active, err error) {
	// get all the non-nil fields and prepare them for the query
	c, i, v := querySlices(a.getFields(aa), 0)

	// sql insert query, primary key provided by sequence
	sqlstr := `
	INSERT INTO public.actives (` + strings.Join(c, ", ") + `)
	VALUES (` + strings.Join(i, ", ") + `)
	RETURNING "id", "token", "state", "used", "created_at", "updated_at"`

	DBLog(sqlstr, v...)
	row := a.DB.QueryRow(sqlstr, v...)
	err = row.Scan(&active.ID, &active.Token, &active.State, &active.Used, &active.CreatedAt, &active.UpdatedAt)
	if err != nil {
		return active, err
	}

	return active, nil
}
