package tempo

import "github.com/matthewmueller/pgx"

// GENERATED BY POGO. DO NOT EDIT.

// FindOne Event by a condition
func (e *Events) FindOne(condition string, params ...interface{}) (event Event, err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `
    SELECT "id", "time", "task", "created_at", "triggered_at", "status", "response", "attempts"
    FROM public.events
    WHERE ` + condition

	DBLog(sqlstr, params...)
	row := e.DB.QueryRow(sqlstr, params...)
	err = row.Scan(&event.ID, &event.Time, &event.Task, &event.CreatedAt, &event.TriggeredAt, &event.Status, &event.Response, &event.Attempts)
	if err != nil {
		if err == pgx.ErrNoRows {
			return event, ErrEventNotFound
		}
		return event, err
	}

	return event, nil
}
