package tempo

import (
 "strings"

 "github.com/pkg/errors"
)

// GENERATED BY POGO. DO NOT EDIT.

// Insert the SchemaMigration to the database.
func (sm *SchemaMigrations) Insert(smsm *SchemaMigration) (schemamigration SchemaMigration, err error) {
 // get all the non-nil fields and prepare them for the query
 c, i, v := querySlices(sm.getFields(smsm), 0)

 // sql insert query, primary key provided by sequence
 sqlstr := `
	INSERT INTO public.schema_migrations (` + strings.Join(c, ", ") + `)
	VALUES (` + strings.Join(i, ", ") + `)
	RETURNING version`

 DBLog(sqlstr, v...)
 row := sm.DB.QueryRow(sqlstr, v...)
 err = row.Scan(&schemamigration.Version)
 if err != nil {
  return schemamigration, errors.Wrap(err, "could not insert into 'schema_migrations'")
 }

 return schemamigration, nil
}
