package tempo

// GENERATED BY POGO. DO NOT EDIT.

// Delete the SchemaMigration from the database.
func (sm *SchemaMigrations) Delete(version *int) (err error) {
 // sql query
 const sqlstr = `
    DELETE FROM public.schema_migrations
    WHERE version = $1
  `

 // run query
 DBLog(sqlstr, version)
 _, err = sm.DB.Exec(sqlstr, version)
 if err != nil {
  return err
 }

 return nil
}
