package tempo

// GENERATED BY POGO. DO NOT EDIT.

// DeleteMany delete many SchemaMigrations by a condition
func (sm *SchemaMigrations) DeleteMany(condition string, params ...interface{}) (err error) {
	// sql select query, primary key provided by sequence
	sqlstr := `DELETE FROM public.schema_migrations WHERE ` + condition

	DBLog(sqlstr, params...)
	_, err = sm.DB.Exec(sqlstr, params...)
	if err != nil {
		return err
	}

	return nil
}
