package tempo

import "strings"

// GENERATED BY POGO. DO NOT EDIT.

// Insert the Task to the database.
func (t *Tasks) Insert(tt *Task) (task Task, err error) {
	// get all the non-nil fields and prepare them for the query
	c, i, v := querySlices(t.getFields(tt), 0)

	// sql insert query, primary key provided by sequence
	sqlstr := `
	INSERT INTO public.tasks (` + strings.Join(c, ", ") + `)
	VALUES (` + strings.Join(i, ", ") + `)
	RETURNING "id", "key", "target", "rate", "offset", "timezone", "rate_type", "rate_options", "status", "target_type", "target_options", "user", "meta", "refreshed_at", "created_at", "updated_at"`

	DBLog(sqlstr, v...)
	row := t.DB.QueryRow(sqlstr, v...)
	err = row.Scan(&task.ID, &task.Key, &task.Target, &task.Rate, &task.Offset, &task.Timezone, &task.RateType, &task.RateOptions, &task.Status, &task.TargetType, &task.TargetOptions, &task.User, &task.Meta, &task.RefreshedAt, &task.CreatedAt, &task.UpdatedAt)
	if err != nil {
		return task, err
	}

	return task, nil
}
