package tempo

// GENERATED BY POGO. DO NOT EDIT.

// Find a team by id
func (u *Users) Find(id *string) (user User, err error) {
 // sql select query, primary key provided by sequence
 sqlstr := `
    SELECT id, role, email, stripe_id, active, access_token, scope, free_events, cost_per_event, total_events, paid_events, token, created_at, updated_at, free_tasks
    FROM public.users
    WHERE id = $1`

 DBLog(sqlstr, id)
 row := u.DB.QueryRow(sqlstr, id)
 err = row.Scan(&user.ID, &user.Role, &user.Email, &user.StripeID, &user.Active, &user.AccessToken, &user.Scope, &user.FreeEvents, &user.CostPerEvent, &user.TotalEvents, &user.PaidEvents, &user.Token, &user.CreatedAt, &user.UpdatedAt, &user.FreeTasks)
 if err != nil {
  return user, err
 }

 return user, nil
}
